revert: test circle ci pipeline [TAROT-2376]
codacy/codacy-trivy pull request #2
Opened 2023-10-06 13:54 UTC by Afonsobli

2023-10-09 16:41 UTC, afsmeira commented on .circleci/config.yml
> +            - publish_docker_local
```suggestion
      - install_trivy_and_download_dbs:
          name: install_trivy_and_download_dbs
          requires:
            - codacy/checkout_and_version
      - build_and_publish_docker:
          name: publish_docker_local
          requires:
            - install_trivy_and_download_dbs
      
```

It needs to be the other way around. First download the images to a well known directory, then copy the contents of the directory to the Docker image when building

2023-10-09 16:43 UTC, afsmeira commented on .circleci/config.yml
> +            curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b . v0.44.1
```suggestion
            # https://aquasecurity.github.io/trivy/v0.45/getting-started/installation/#install-script
            curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b . v0.44.1
```

2023-10-10 10:03 UTC, Afonsobli commented on .circleci/config.yml
> +            curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b . v0.44.1
thank you!

2023-10-11 08:42 UTC, afsmeira approved these changes
LGTM. Did the scheduled workflow already run?

2023-10-11 09:23 UTC, afsmeira requested changes
Wait, you need to change the Dockerfile to copy the cache folder inside the image.

2023-10-11 10:17 UTC, Afonsobli commented
> LGTM. Did the scheduled workflow already run?

it did!

2023-10-11 11:24 UTC, afsmeira reviewed
I think you need to add a `cache` entry in `.gitignore`.

2023-10-11 11:24 UTC, afsmeira commented on Dockerfile
> +COPY /cache /dist/cache/codacy-trivy
```suggestion
COPY cache/ /dist/cache/codacy-trivy
```

2023-10-11 14:24 UTC, afsmeira approved these changes

2023-10-11 14:24 UTC, afsmeira commented on Dockerfile
> +COPY --from=builder /src/cache/ /dist/cache/codacy-trivy
```
COPY --from=builder --chown=docker:docker /src/bin /dist/bin
COPY --from=builder --chown=docker:docker /src/docs /docs 
COPY --from=builder --chown=docker:docker /src/cache/ /dist/cache/codacy-trivy
```

2023-10-11 14:29 UTC, afsmeira approved these changes

2023-10-11 14:33 UTC, merged